server:
    port: 8888
spring:
    application:
        name: Bestiario
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    datasource:
        url: jdbc:postgresql://localhost:5432/bestiario?serverTimeZone=America/SÃ£o_Paulo
        username: postgres
        password: postdba
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    flyway:
        enabled: none
        locations: classpath:db/migration